### PR TITLE
Code Converted to the new syntax of ECMAScript (Version 6) with the tool

### PR DESCRIPTION
**Pull request by DVSCross**
ECMA  Class Parser (A Tool on development by me).This first version,
basically identifies the class-like structures, on codes based in Object
Oriented Programming, and convert it to the new Syntax.Some samples
and explanations at the page http://es6-features.org/#ClassDefinition. All
the behaviors of the game keeps the same and were teste Feedback would
be nice and will encourage this work, that has the objective to be published 
on Workshop of Software Visualization, Evolution, and Maintenance (VEM).
Contact-me at danielvsc@dcc.ufmg.br.
Best Regards.
Thanks!

### CODE REVIEW

**Comment by iirelu** [comment]
Thank you for the effort but I really don't see why this is needed for 2048. The code style improvements are limited, and this would likely break backwards compatibility for no real reason.

**Comment by DVSCross** [comment]
Thanks for the quick feedback!
Just to register on my results, can you give me a position about the class identification?
(Just if some class wasn't to be considered as one, for example)

Best Regards.

**Comment by gabrielecirulli** [comment]
From a quick inspection your tool doesn't seem to respect code style and spacing. There are a few instances of `function ()` being transformed into `function()` and a lot of empty lines being squashed. Those are generally important to keep. I also saw an instance of an inline if (`if (foo) bar()`) being transformed into a block, which again doesn't seem to respect the original author's semantics and style choices.

**Comment by gabrielecirulli** [comment]
Hope this feedback helps you develop it, however I agree with @iirelu's premise that this kind of change is not necessary and overly risky at this time.

**Pull request closed without merging**
