### PR TITLE
Adding Android imagery

### PR DESCRIPTION
**Pull request by Gustavo6046**
Yes, I know one piece was borrowed from Apple imagery.

### CODE REVIEW

**Comment by sigod** [comment]
Forgive me my ignorance. But what are these images for?

**Comment by birdspider** [comment]
@sigod: beware of the trolls: https://github.com/KSP-CKAN/CKAN/issues/1314

**Comment by Gustavo6046** [comment]
I am sorry, i don't understand what you want, but I just wish now to help adapt this game to Android. Everyone is calling me troll and doing that link since I done the *"issue"*... for some reason... I make nice scripts, and [this](https://github.com/Gustavo6046/LP3) is a proof. I **never** had intent to harm anyone or any project... and will **never** have...

**Comment by Gustavo6046** [comment]
Oh, I almost forgot to answer your question. These images are for when running 2048 in an **Android device**: two startup images *(horizontal, vertical)* for when the app is loading; and one image for  playing it, which I'm sure you already know.

**Pull request closed without merging**
