### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by maxrimue** [comment]
I consider this content a bit explicit

**Comment by sigod** [comment]
Interesting. Google doesn't know this images. :)

**Comment by maxrimue** [comment]
@ghost You'll have to delete your fork to completely delete the photos, they're still viewable in the older commit

**Comment by sigod** [comment]
Hm. Look like this files now in main repository.

@ghost If want to delete your account: open [settings/admin](https://github.com/settings/admin) and press `Delete your account`.

**Comment by wrexroad** [comment]
He did delete his account, that is why his name changed from ajangus to ghost. I'm not sure if there is an easy way to remove those files. It seems like the Github issue tracker (the part of the system that manages pull requests) is separate from the git repository. Everything is saved in the issue tracker for posterity, and I have not found a way to actually delete a pull request. If the files are to be removed it will probably have to be done by an admin of this repo, and possibly with the help of Github staff (which I'm sure they will want to do considering the nature of the files).

**Comment by iirelu** [comment]
I've contacted Github support and asked them to delete this PR and the images.

**Pull request closed without merging**
