### PR TITLE
Tracking number of moves and direction for best score and current score

### PR DESCRIPTION
**Pull request by sharvani198**
Added a new feature to support scoring, number of moves.
the total number of moves are shown, divided into the direction of moves.
the ratio of the moves in each direction will be represented by the shade of the arrow.
the moves for the best score are stored.

### CODE REVIEW

**Comment by iirelu** [comment]
blender

Hmm, the code is good enough albeit with a bunch of incorrect whitespace, but the way it looks is awkward and I can't quite see the point in tracking directions.

**Comment by gabrielecirulli** [comment]
If this has to be done, I'd suggest it's implemented like it is in the 2048 app (the one I made, not the popular one). The move count is shown as small text below the board, in a non-obtrusive way. 

Also, in my opinion there's no point at all in showing the "best overall" move count, if that's the reason why two numbers are displayed. =

**Comment by sharvani198** [comment]
What I thought was.- if you knew the type of moves made to get to your
previous best score, at any time you can change your move pattern to match
the best pattern.
I agree that it looks a little smashed , but if the feature is acceptable
then design can be changed.  Just showing number of moves would by useless,
 it has to include direction count.

**Comment by gabrielecirulli** [comment]
In that case, I wouldn't consider it important enough to be included in the core of the game like this. Such a display would take a certain amount of space no matter where you put it and I'm not sure the value it provides justifies the visual changes. That's just my opinion though. I would still like to hear what the others think.

**Comment by Bentong021** [comment]
https://github.com/gabrielecirulli/2048/pull/283

**Pull request closed without merging**
