### PR TITLE
changed wording

### PR DESCRIPTION
**Pull request by jcarey987**

### CODE REVIEW

**Comment by Rabadash8820** [comment]
Why oh why would you submit a pull request for this?

**Comment by lyan426** [comment]
Hello man. My English is not so good,and dont really know how to use the Github. I think I did something wrong but dont know what to do next. 发自网易邮箱手机版 在2017年09月21日 04:08，Daniel Vicarel 写道： Why oh why would you submit a pull request for this? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jcarey987** [comment]
@Rabadash8820  - I am new to GitHub and clicked too many buttons... I was trying to push the changes to my version and mistakenly pushed them to the master

**Comment by Rabadash8820** [comment]
@jcarey987 Understandable.  If that's the case, you should [close](https://help.github.com/articles/closing-a-pull-request/) this PR yourself and spare the moderators the annoyance.

**Pull request closed without merging**
