### PR TITLE
Typescript Refactored Version.

### PR DESCRIPTION
**Pull request by electricessence**
Why?  Why not!??

### CODE REVIEW

**Comment by electricessence** [comment]
https://www.youtube.com/watch?v=xDJWuuLCHIo

**Comment by iirelu** [comment]
Whoa, I watched your video, and this seems great! A huge improvement in code quality all around, and you probably fixed countless unknown bugs. I'd appreciate all those identically-described commits being squashed into one, but apart from that I'd love to merge this.

I'm going to wait and see what the other maintainers (cc @gabrielecirulli, @sigod) think of this before merging it.

**Comment by gabrielecirulli** [comment]
Interesting work, I'll have a look later this week. Just to set
expectations right: I can't promise that we merge this, as it is still a
radical change. I will give it proper consideration though.

**Comment by electricessence** [comment]
@gabrielecirulli I totally understand if this goes too far LOL.|
But I think where it really gets interesting is class inheritance.  By using Point2D as a base class for example.
You'll also find as any 'game' or app like this gains complexity, you can really benefit from the reuse.

Someone should pull and test this branch to make sure I'm not crazy. :P

**Comment by Andrew1431** [comment]
You should `.gitignore` any compiled file / source map. Would make this pr much smaller and cleaner.

**Comment by electricessence** [comment]
@Andrew1431, I could, but then it wouldn't work straight out of the box.
Currently, this version doesn't change where the JS files lived.  So I'm more inclined to keep the built files.  That way if someone doesn't have TS, they can still download and run/test it.

**Comment by Insayt** [comment]
##Heq

**Comment by Insayt** [comment]
ic3

**Comment by Insayt** [comment]
```javascript
var a = 10;
a ++;
```

**Comment by Insayt** [comment]
aaaaaaa
vvvvvvvv
shot2x

**Comment by Insayt** [comment]
[_job_offer_袠薪褋邪泄褌褍 袗谢械泻褋邪薪写褉�.pdf](https://github.com/gabrielecirulli/2048/files/1346071/_job_offer_.pdf)

**Pull request closed without merging**
