### PR TITLE
Updated contributors username.

### PR DESCRIPTION
**Pull request by marcingajda**
I changed my GitHub username and the old link doesn't work anymore.

### CODE REVIEW

**Comment by zaraeszara** [comment]
Tonino Lamborghini Energy Drink Au Maroc TLED

**Comment by iirelu** [comment]
Cool! Confirmed with #46

**Comment by bidwell1** [comment]
hi we will talk some other time love you all

**Comment by bidwell1** [comment]
#236360#

**Comment by bidwell1** [comment]
#1

**Pull request merged**
