### PR TITLE
Pull request for adding a stopwatch along with a best time storage(Issue #334)

### PR DESCRIPTION
**Pull request by PeriGK**
Hi,

Inspired by the request on issue #334, I have done some work, to allow the player to play a timed game.

In a nutshell: A player clicks the Timed Game button and then a stopwatch starts counting. If the players wins the time is recorded as her best time. If the player doesnt win the game, the best time remains unchanged.
The reason for that, is that most people can lose the game in a matter of seconds and this is surely not a sign of the player being competent. But the point of the change is to keep track of the "fast-winners". :)
Please let me know your thoughts.

Regards,
PeriGK

### CODE REVIEW

**Comment by luis140219** [comment]
+1. I agree with this change. It just adds functionality to the game and makes it more fun. Most pulls to this repo are about changing colours or replacing numbers with images.

**Comment by iirelu** [comment]
We're not interested in making major changes to the base 2048 game, and at this point making your own improved fork is more likely to be popular, anyway.

**Comment by PeriGK** [comment]
That's a bit sad but you are the masters of the repo and I respect your decision. 

@iirelu could you please elaborate a bit this part: 

> and at this point making your own improved fork is more likely to be popular, anyway.

I dont think I get it.

cheers,
P.

>

**Comment by sigod** [comment]
@PeriGK You can fork this repository, make all changes and publish it with [GitHub Pages](https://pages.github.com/).

**Pull request closed without merging**
